---
# tasks file for ansible-command
- name : Install packages on guests.
  yum: name={{ item }} state=latest
  with_items:
    - yum-utils

- name : Run package cleanup command
  command : /bin/package-cleanup -y --oldkernels --count=1
