---
# tasks file for ansible-command
- name : Install packages on guests.
  yum: "pkgs={{ item }} state=latest"
  with_items:
    - qemu-guest-agent
    - yum-utils

- name : Run package cleanup command
  command : /bin/package-cleanup -y --oldkernels --count=1
dd

- name : Enable qemu-guest-agent
  service:
    name: qemu-guest-agent
    enabled: yes
    state: started
